version: "3.8"
services: 
  client:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    command: sh -c "yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"